version: "3"
services:
  mysql:
    image: mysql:5
    container_name: design-mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    # command: --init-file ./init.sql
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "student_elective_system"
    networks:
      - net-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: design-pmd
    ports:
      - "7777:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: design-mysql
    networks:
      - net-mysql

networks:
    net-mysql: